version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: gaming-crafty_proxy_1
      APP_PORT: 80

  proxy:
    image: nginx:alpine
    restart: on-failure
    depends_on:
      - server
    command:
      - /bin/sh
      - -c
      - |
        cat > /etc/nginx/conf.d/default.conf <<'EOF'
        server {
          listen 80;

          location / {
            proxy_pass https://server:8443;
            proxy_ssl_verify off;

            proxy_http_version 1.1;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
          }
        }
        EOF

        nginx -g 'daemon off;'

  server:
    image: arcadiatechnology/crafty-4:4.4.9
    restart: on-failure

    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC

    ports:
      - "18444:8443"
      - "8000:8000"
      - "8523:8123"
      - "19132:19132/udp"
      - "25500-25600:25500-25600"

    volumes:
      - ${APP_DATA_DIR}/data/app/config:/crafty/app/config
      - ${APP_DATA_DIR}/data/logs:/crafty/logs
      - ${APP_DATA_DIR}/data/import:/crafty/import
      - ${APP_DATA_DIR}/data/backups:/crafty/backups
      - ${APP_DATA_DIR}/data/servers:/crafty/servers